import Head from 'next/head'
import { useEffect, useState } from 'react';
import Axios from 'services/axios';
import styles from '../styles/Home.module.css'

export default function Home() {
    const [filters , setFilter] = useState({name: ''})
    const [todoList, setTodoList] = useState([])

    function onSubmit(evt) {
        evt.preventDefault();
    }

    async function fetchTodoList() {
        let response = await Axios.get('todo', filters)        
        setTodoList(response.data.data)
    }

    function onFilterChange(evt) {
        setFilter({name: evt.target.value})
    }

    useEffect(() => {
        fetchTodoList()
    }, [filters])

    return (
        <div className={styles.container}>
            <Head>
                <title>Todo App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to Todo App
                </h1>
                <form action="" onSubmit={onSubmit}>
                    <div>
                        <input type="text" autoComplete={false} value={filters.name} className={styles.input_text} onChange={onFilterChange}/>
                        <div className={styles.input_message}>
                            { filters.name }
                        </div>
                    </div>
                </form>

                <table className={styles.table}>
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Todo</th>
                            <th>Is Completed</th>
                            <th>Created At</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {todoList.length ? todoList.map( (item, index) => 
                            <tr key={ index }>
                                <td>{ item.id }</td>
                                <td>{ item.name }</td>
                                <td>{ item.isCompleted ? 'YES' : 'NO' }</td>
                                <td>{ item.createdAt }</td>
                                <td>

                                </td>
                            </tr>
                        ) : (
                            <tr>
                                <td colSpan={5}><h3>No result</h3></td>
                            </tr>
                        )}
                    </tbody>
                </table>
            </main>
        </div>
    )
}
